### ISSUE TITLE
Problema/erro Processos Comerciais (1h)

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#11]
Boa tarde Rui,

a aplicação dá erro na área de Processos Comerciais
![image](https://user-images.githubusercontent.com/60134619/75556295-d914b180-5a35-11ea-8aed-fa12c7cdd545.png)

**Comment by ruicarvoeiro** [comment]
Bastidores OLIRACK19" 36U P 600x1000
Têm de voltar a criar esta proposta.
Certifiquem-se que desta vez colocam uma entedida existente.

**Comment by nunosantos-cso** [comment]
Boa tarde Rui,

ao criar nova proposta deu este erro:
![image](https://user-images.githubusercontent.com/60134619/75988317-49657c00-5ee9-11ea-8fc3-1d78e68dc3ad.png)
