### ISSUE TITLE
Erro na BIO

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#13]
Boa tarde Rui,

ocorreu erro na área de propostas comerciais
![image](https://user-images.githubusercontent.com/60134619/87327540-146ad500-c52c-11ea-8fb7-4eff08f8c867.png)
Solicito resolução,

Abraço, Nuno Santos-CSO

**Comment by ruicarvoeiro** [comment]
nuno, depois tens de voltar a colocar esta proposta
![imagem](https://user-images.githubusercontent.com/28627507/87771611-85eea000-c818-11ea-8695-71825c0e97ea.png)
