### ISSUE TITLE
Erro na BIO propostas comerciais

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#14]
Bom dia Rui, solicito a reposição do serviço devido à seguinte mensagem de erro:
![image](https://user-images.githubusercontent.com/60134619/96985893-ceed7900-1518-11eb-9856-d8edd6c895b4.png)
Abraço,

Nuno Santos - CSO

**Comment by ruicarvoeiro** [comment]
Erro corrigido
