### ISSUE TITLE
Proveitos e Custos - Prioridade(12h)

### ISSUE THREAD

**Issue by ruicarvoeiro** [ruicarvoeiro/bio_cso#2]
Está a adicionar zeros,
problema no DetalhePRocesso.aspx

**Comment by nunosantos-cso** [comment]
Rui, a resolução do carregamento dos proveitos e custos na BIO  é urgente para que possamos efectuar análises de gestão à nossa actividade.

**Comment by ruicarvoeiro** [comment]
Se tiveres algo urgente para colocar diz-me que eu martelo na BD, tal como te disse isto é uma tarefa que vai exigir algum tempo, tempo esse que não tenho.

**Comment by nunosantos-cso** [comment]
Deixou de ser possível carregar os proveitos e custos. No final da manhã consegui experimentalmente carregar com sucesso, actualmente deicou de ser possível. Inclusivamente a informação carregada desapareceu.
![image](https://user-images.githubusercontent.com/60134619/73549831-4c2d0700-443b-11ea-93ce-881d4fcd8e38.png)
![image](https://user-images.githubusercontent.com/60134619/73549865-5fd86d80-443b-11ea-892a-91fd094d11a9.png)

**Comment by ruicarvoeiro** [comment]
@nunosantos-cso  já consegui, finalmente, resolver o problema! Dá-me um ok para fechar este tópico!

**Comment by nunosantos-cso** [comment]
![image](https://user-images.githubusercontent.com/60134619/74017567-5f385d80-498c-11ea-830b-956e36829539.png)
Não adiciona os Proveitos e os custos neste processo

**Comment by nunosantos-cso** [comment]
![image](https://user-images.githubusercontent.com/60134619/74017969-00bfaf00-498d-11ea-8592-b16054b01e39.png)
Anomalia no campo margem, caso único

**Comment by ruicarvoeiro** [comment]
Tenta limpar a cache. Creio que são casos pontuais
