### ISSUE TITLE
Criação de Entidade - mensagem de erro

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#21]
Bom dia Rui, 

ao tentar criar uma nova Entidade aparece a seguinte mensagem de erro:

![image](https://user-images.githubusercontent.com/60134619/98669049-b7035b00-2348-11eb-8fc8-d5de31d94608.png)

Cumprimentos.

Nuno Santos - CSO

**Comment by ruicarvoeiro** [comment]
Bom dia Nuno,

Dá sempre esse erro sempre que crias uma entidade? Só para conseguir replicar o erro

**Comment by nunosantos-cso** [comment]
Bom dia,

Sim dá sempre este erro na criação da entidade.

Cumps,

Nuno Santos - CSO

De: Carvoeiro <notifications@github.com>
Enviada: 10 de novembro de 2020 12:15
Para: ruicarvoeiro/bio_cso <bio_cso@noreply.github.com>
Cc: Nuno Santos <nuno.santos@cso.pt>; Author <author@noreply.github.com>
Assunto: Re: [ruicarvoeiro/bio_cso] Criação de Entidade - mensagem de erro (#21)


Bom dia Nuno,

Dá sempre esse erro sempre que crias uma entidade? Só para conseguir replicar o erro

**Comment by ruicarvoeiro** [comment]
Ok, podes testar sff?

**Comment by nunosantos-cso** [comment]
Ok está a bombar.Obrigado.

De: Carvoeiro <notifications@github.com>
Enviada: 10 de novembro de 2020 12:51
Para: ruicarvoeiro/bio_cso <bio_cso@noreply.github.com>
Cc: Nuno Santos <nuno.santos@cso.pt>; Author <author@noreply.github.com>
Assunto: Re: [ruicarvoeiro/bio_cso] Criação de Entidade - mensagem de erro (#21)


Ok, podes testar sff?
