### ISSUE TITLE
Desenvolvimento para faturação faseada

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#22]
Boa noite Rui, pretendemos discutir desenvolvimento de opções para faturação faseada. O Jorge Miranda pede para falares com ele para ver a melhor forma de atingirmos este objetivo. Abraço.

**Comment by ruicarvoeiro** [comment]
Boa noite Nuno. Tem urgência? Só devo conseguir em Fevereiro
 Abraço
