### ISSUE TITLE
Problema na passagem para proposta adjudicada

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#3]
Bom dia Rui, 
ao passar este processo de proposta pendente:
Pegop | CSO Card | CSO192008 
para proposta adjudicada aparece novamente um processo com uma referência distinta:
GSTEP | CSO Card | CSO202018 | 2020-01-21
solicitamos resolução.

**Comment by ruicarvoeiro** [comment]
Problema a obter RowIndex na gridview da classe processos.aspx
