### ISSUE TITLE
Run Time Error

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#4]
![image](https://user-images.githubusercontent.com/60134619/72913609-4cd7e600-3d35-11ea-9eb4-580249ed275f.png)

Boa tarde Rui,

a aplicação começou a efectuar Runtime Error, envio a imagem para veres em preview.

**Comment by nunosantos-cso** [comment]
Rui, suspeito que seja o tamanho do ficheiro 12MB, coloquei outro ficheiro mais pequeno e não deu erro.

**Comment by ruicarvoeiro** [comment]
Nuno, consegues voltar a tentar o que gerou este erro a ver se ainda acontece?

**Comment by nunosantos-cso** [comment]
![image](https://user-images.githubusercontent.com/60134619/73356783-fc134080-4292-11ea-8405-86aaaa084cba.png)

tentei carregar um ficheiro de 6MB

**Comment by ruicarvoeiro** [comment]
Same as #6
