### ISSUE TITLE
Procedimento para realização de backup

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#5]
Boa tarde Rui,
Solicitamos procedimento para realização de backup automático e manual.

Cumps

**Comment by ruicarvoeiro** [comment]
Bom dia,
Foi partilhado com o Tiago este link https://www.fmsinc.com/free/NewTips/SQL/SQLServerExpressDatabase/Automated_Backup.asp

**Comment by ruicarvoeiro** [comment]
Nuno, indica-me se o objetivo é eu fazer esses backups ou vocês tratam disso?

**Comment by nunosantos-cso** [comment]
Somos nós que realizamos o backup, ainda ontem o Pedro Ferreira fez um.
