### ISSUE TITLE
Tamanho de ficheiros

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#6]
Verificámos que a introdução de um ficheiro com 12MB não é possível dando erro. Solicitamos o incremento para até 50 MB.

**Comment by ruicarvoeiro** [comment]
O erro que dá é semelhante ao Runtime #4

**Comment by ruicarvoeiro** [comment]
https://stackoverflow.com/questions/288612/how-to-increase-the-max-upload-file-size-in-asp-net

**Comment by ruicarvoeiro** [comment]
@nunosantos-cso 
Esta situação já esta resolvida?

**Comment by nunosantos-cso** [comment]
Testei um ficheiro de 7MB com sucesso
