### ISSUE TITLE
Problema abertura de ficheiros extensões

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#7]
Rui,

Verificamos que todos os processos abaixo da Refª191754 não têm extensão associada, as duas extensões possíveis são : 

**.msg** normalmente associada aos ficheiros de adjudicação (pode haver encomendas em pdf)-abertura com outlook.
**.pdf** normalmente associados à proposta comercial, factura de fornecedor, factura cliente e alguns ficheiros de adjudicação abertura com acrobat reader.

![image](https://user-images.githubusercontent.com/60134619/73177053-e15f9100-4105-11ea-92a1-7fac6be2e6d5.png)

Existe forma de resolver este problema?

**Comment by ruicarvoeiro** [comment]
Nestes casos não é possível averiguar qual a terminação, foi mesmo  por isso que não a coloquei. Tens de martelar a extensão.
