### ISSUE TITLE
Problema ficheiros com pesquisa de entidade(1h)

### ISSUE THREAD

**Issue by nunosantos-cso** [ruicarvoeiro/bio_cso#8]
Rui,

ao realizar nas propostas adjudicadas uma pesquisa por entidade, os ficheiros carregados não correspondem ao processo ou à entidade da pesquisa.

É necessário validar esta situação.
![image](https://user-images.githubusercontent.com/60134619/73186902-6eabe100-4118-11ea-9197-a439eada10f9.png)

**Comment by ruicarvoeiro** [comment]
Bom dia Nuno, de todas as propostas?

**Comment by nunosantos-cso** [comment]
Sim, seleccionas uma entidade aparecem todos os processos da mesma. Quando vais aos Ficheiros verificas que não correspondem ao processo/referência ou entidade.

**Comment by nunosantos-cso** [comment]
Creio que coloca sempre os ficheiros da ultima proposta adjudicada

**Comment by ruicarvoeiro** [comment]
Ok, vou analisar.

**Comment by ruicarvoeiro** [comment]
Erro na escolha no RowIndex, vai sempre para a primeira
Corrigir em Processos_Adjudicados.aspx criar GridView2_RowCommand e GridView3_RowCommand

**Comment by ruicarvoeiro** [comment]
@nunosantos-cso  já incrementei até 50 MB, tenta por favor inserir um ficheiro maior de 4MB (que por default era esse o limite)

**Comment by ruicarvoeiro** [comment]
Resolvi este problema também, confirma
